---------------------------------------------------------------------------------------------------------
---- 카테고리+헬다

CREATE OR REPLACE VIEW MYPAGEBABYINFO
AS
SELECT  HD_CODE,
        HD_DATE,
        HD_CACODE,
        HD_BBSUCODE,
        HD_BBCODE,
        HD_VALUE,
        CA_NAME,
        CA_TYPE
FROM HD INNER JOIN CA ON CA.CA_CODE = HD.HD_CACODE;

---- 최신 키
CREATE OR REPLACE VIEW BABYRECENTHEIGHT
AS
select HD_BBSUCODE AS HSUCODE,HD_BBCODE AS HBABYCODE ,CA_NAME, HD_VALUE AS BBHEIGHT
FROM MYPAGEBABYINFO  
WHERE (HD_BBSUCODE,HD_BBCODE,HD_CACODE, HD_DATE) 
                        IN (
                        SELECT HD_BBSUCODE,HD_BBCODE, HD_CACODE, MAX(HD_DATE) AS HD_DATE 
                            FROM HEALTHDIARY 
                            WHERE HD_CACODE = '02'
                            GROUP BY HD_BBSUCODE,HD_BBCODE,HD_CACODE
                       )AND CA_NAME = 'HEIGHT'
                    ORDER BY HD_BBSUCODE,HD_BBCODE,HD_CACODE;
SELECT*FROM CA;
COMMIT;
---- 최신 몸무게
CREATE OR REPLACE VIEW BABYRECENTWEIGHT
AS
select HD_BBSUCODE AS WSUCODE,HD_BBCODE AS WBABYCODE ,CA_NAME, HD_VALUE AS BBWEIGHT
                    FROM MYPAGEBABYINFO  
                    WHERE (HD_BBSUCODE,HD_BBCODE,HD_CACODE, HD_DATE) 
                    IN (
                        SELECT HD_BBSUCODE,HD_BBCODE, HD_CACODE, MAX(HD_DATE) AS HD_DATE
                            FROM HEALTHDIARY
                            WHERE HD_CACODE = '01'
                            GROUP BY HD_BBSUCODE,HD_BBCODE,HD_CACODE
                       )AND CA_NAME = 'WEIGHT'
                    ORDER BY HD_BBSUCODE,HD_BBCODE,HD_CACODE;

-- 최신키+최신몸무게

SELECT BB_CODE AS BBCODE, BB_SUCODE AS SUCODE, BB_NAME AS BBNAME, TO_CHAR(BB_BIRTHDAY,'YYYY-MM-DD') AS BBBIRTHDAY, BBWEIGHT, BBHEIGHT,BB_PHOTO AS BBPHOTO
FROM BB LEFT OUTER JOIN BABYRECENTWEIGHT ON (BB_CODE = WBABYCODE AND BB_SUCODE = WSUCODE)
        LEFT OUTER JOIN BABYRECENTHEIGHT ON (BB_CODE = HBABYCODE AND BB_SUCODE = HSUCODE)
WHERE BB_SUCODE = '2409449450'
ORDER BY BBCODE;

-- 예약정보 검색
SELECT COCODE AS RESCOCODE,
       CONAME AS RESCONAME,
       RECODE AS RESCODE,
       REDATE AS RESDATE,
       BBNAME AS RESBBNAME
FROM CORE WHERE TO_CHAR(REDATE, 'YYMMDD') = #{date} AND SUCODE = #{suCode} AND STATUS ='CP';
-- 일정정보 검색
SELECT SC_CODE AS SCHEDULECODE,
       TO_CHAR(SC_DATE,'YYYYMMDD') AS SCHEDULEDATE,
       SC_CONTENT AS SCHEDULENAME
FROM SC WHERE TO_CHAR(SC_DATE,'YYMMDD') = '220905' AND SC_SUCODE = '2411751690';
-- 건강일기 작성여부 검색
SELECT COUNT(*) 
FROM HD WHERE HD_BBSUCODE = '2411751690' AND TO_CHAR(HD_DATE, 'YYMMDD') = '220905';
-- 공유일기 작성여부 검색
SELECT COUNT(*)
FROM DD WHERE DD_SUCODE = '2411751690' AND TO_CHAR(DD_DATE, 'YYMMDD') = '220905';


-- 개인일정 새로운 코드 받아오기 -- 맥스값이 없다면 YYYYMMDD+01~~
SELECT NVL(MAX(SC_CODE)+1 , (REPLACE(#{scheduleDate}, '-', '')|| '01'))
FROM SC WHERE SC_SUCODE = #{suCode} AND TO_CHAR(SC_DATE,'YYYY-MM-DD')=#{scheduleDate}