--세션에 저장할 유저 정보 조회 뷰
CREATE OR REPLACE VIEW ACCESSINFO AS
SELECT  SU_CODE AS SUCODE,
        SU_NAME AS SUNAME,
        SU_PHONE AS SUPHONE,
        SU_EMAIL AS SUEMAIL,
        SU_NICKNAME AS SUNICKNAME
FROM SU;

--유저 아이정보 조회 뷰
CREATE OR REPLACE VIEW TOTALBABYINFO AS
SELECT  BB_CODE AS BBCODE,
        BB_SUCODE AS SUCODE,
        BB_NAME AS BBNAME,
        BB_BIRTHDAY AS BBBIRTHDAY
FROM BB;

--건강일기 리스트 뷰
CREATE OR REPLACE VIEW HEALTHDIARYLIST AS
SELECT  HD_CODE AS HDCODE,
        HD_DATE AS HDDATE,
        HD_BBSUCODE AS SUCODE,
        HD_BBCODE AS BBCODE,
        BB_NAME AS BBNAME
FROM HD INNER JOIN BB ON BB_CODE = HD_BBCODE AND BB_SUCODE = HD_BBSUCODE
GROUP BY HD_CODE, HD_DATE, HD_BBSUCODE, HD_BBCODE, BB_NAME;

--건강일기 디테일 뷰
CREATE OR REPLACE VIEW DETAILHEALTHDIARY AS
SELECT  HD_CODE AS HDCODE,
        TO_CHAR(HD_DATE,'YYYYMMDDHH24MISS') AS HDDATE,
        HD_BBSUCODE AS SUCODE,
        BB_CODE AS BBCODE,
        BB_NAME AS BBNAME,
        W1.WEIGHT AS BBWEIGHT,
        H2.HEIGHT AS BBHEIGHT,
        H3.HEAD AS HEAD,
        F4.FOOT AS FOOT,
        T5.TEMPERATURE AS TEMPERATURE,
        S6.SLEEP AS SLEEP,
        D7.DEFECATION AS DEFECATION,
        D8.DEFSTATUS AS DEFSTATUS,
        M9.MEAL AS MEAL,
        M10.MEMO AS MEMO
FROM HD INNER JOIN BB ON HD_BBSUCODE = BB_SUCODE AND HD_BBCODE = BB_CODE
        LEFT OUTER JOIN HDWEIGHT W1 ON W1.HDCODE = HD_CODE AND W1.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDHEIGHT H2 ON H2.HDCODE = HD_CODE AND H2.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDHEAD H3 ON H3.HDCODE = HD_CODE AND H3.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDFOOT F4 ON F4.HDCODE = HD_CODE AND F4.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDTEMPERATURE T5 ON T5.HDCODE = HD_CODE AND T5.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDSLEEP S6 ON S6.HDCODE = HD_CODE AND S6.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDDEFECATION D7 ON D7.HDCODE = HD_CODE AND D7.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDDEFSTATUS D8 ON D8.HDCODE = HD_CODE AND D8.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDMEAL M9 ON M9.HDCODE = HD_CODE AND M9.SUCODE = HD_BBSUCODE
        LEFT OUTER JOIN HDMEMO M10 ON M10.HDCODE = HD_CODE AND M10.SUCODE = HD_BBSUCODE
GROUP BY HD_CODE, HD_DATE, HD_BBSUCODE, BB_CODE, BB_NAME, WEIGHT, HEIGHT, HEAD, FOOT, TEMPERATURE, SLEEP, DEFECATION, DEFSTATUS, MEAL, MEMO;
--건강일기 항목 뷰
CREATE OR REPLACE VIEW HDWEIGHT
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS WEIGHT
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '01';
CREATE OR REPLACE VIEW HDHEIGHT
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS HEIGHT
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '02';
CREATE OR REPLACE VIEW HDHEAD
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS HEAD
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '03';
CREATE OR REPLACE VIEW HDFOOT
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS FOOT
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '04';
CREATE OR REPLACE VIEW HDTEMPERATURE
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS TEMPERATURE
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '05';
CREATE OR REPLACE VIEW HDSLEEP
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS SLEEP
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '06';
CREATE OR REPLACE VIEW HDDEFECATION
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS DEFECATION
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '07';
CREATE OR REPLACE VIEW HDDEFSTATUS
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS DEFSTATUS
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '08';
CREATE OR REPLACE VIEW HDMEAL
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS MEAL
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '09';
CREATE OR REPLACE VIEW HDMEMO
AS
SELECT  CA_CODE AS CACODE,
        CA_NAME AS CANAME,
        HD_CODE AS HDCODE,
        HD_BBSUCODE AS SUCODE,
        HD_VALUE AS MEMO
FROM CA INNER JOIN HD ON CA_CODE = HD_CACODE
WHERE CA_CODE = '10';
SELECT * FROM RE;

--의사소견 조회 뷰
CREATE OR REPLACE VIEW COMMENTLIST AS 
SELECT  RE_DATE AS RESDATE,
        RE_DOCOCODE AS COCODE,
        CO_NAME AS CONAME,
        RE_DOCODE AS DOCODE,
        DO_NAME AS DONAME,
        RE_BBSUCODE AS SUCODE,
        RE_BBCODE AS BBCODE,
        BB_NAME AS BBNAME,
        RE_COMMENT AS DOCOMMENT
FROM RE INNER JOIN CO ON RE_DOCOCODE = CO_CODE
        INNER JOIN DO ON RE_DOCODE = DO_CODE AND RE_DOCOCODE = DO_COCODE
        INNER JOIN BB ON RE_BBCODE = BB_CODE AND RE_BBSUCODE = BB_SUCODE;

--감성일기 작성 여부
SELECT COUNT(DD_CODE) AS DAILYDIARY, TO_CHAR(DD_DATE,'YYYY-MM-DD') AS DDDATE, DD_SUCODE 
FROM DD 
WHERE TO_CHAR(DD_DATE,'YYYY-MM') = TO_CHAR(#{date},'YYYY-MM')
GROUP BY TO_CHAR(DD_DATE,'YYYY-MM-DD'), DD_SUCODE;
--건강일기 작성 여부
SELECT COUNT(HD_CODE) AS HEALTHDIARY, TO_CHAR(HD_DATE,'YYYY-MM-DD') AS HDDATE, HD_BBSUCODE 
FROM HD
WHERE TO_CHAR(HD_DATE,'YYYY-MM') = TO_CHAR(#{date},'YYYY-MM')
GROUP BY TO_CHAR(HD_DATE,'YYYY-MM-DD'), HD_BBSUCODE;
--일정 여부
SELECT * FROM RE;
SELECT COUNT(RE_CODE) AS RESERVATION, TO_CHAR(RE_DATE,'YYYY-MM-DD') AS RESDATE, RE_BBSUCODE
FROM RE
WHERE RE_BBSUCODE  = '2411751690' AND RE_RCCODE = 'CP'
GROUP BY TO_CHAR(RE_DATE,'YYYY-MM-DD'), RE_BBSUCODE;
--일정 여부
SELECT COUNT(SC_CODE) AS SCHEDULE, TO_CHAR(SC_DATE,'YYYY-MM-DD') AS SCDATE, SC_SUCODE
FROM SC
WHERE TO_CHAR(SC_DATE,'YYYY-MM') = TO_CHAR(#{date},'YYYY-MM')
GROUP BY TO_CHAR(SC_DATE,'YYYY-MM-DD'), SC_SUCODE;

--아기 생일(여러개)
SELECT TO_CHAR(BB_BIRTHDAY,'YYYY-MM-DD') AS BABYBIRTHDAY, BB_NAME AS BABYNAME
FROM BB
WHERE BB_SUCODE = #{suCode};
