--예약정보 뷰
CREATE OR REPLACE VIEW RESINFO
AS
SELECT SUBSTR(TO_CHAR(RE_DATE), 1, 8) AS RESDATE, BB_NAME AS RESBBNAME, RE_DOCODE AS RESDOCODE, RE_RCCODE AS RCCODE, RE_DOCOCODE AS COCODE, DO_NAME AS RESDONAME, RE_CODE AS RESCODE
FROM RESERVATION RES INNER JOIN BABY BB ON RES.RE_BBSUCODE = BB.BB_SUCODE
                                        AND RES.RE_BBCODE = BB.BB_CODE
                     INNER JOIN DOCTOR DOC ON RES.RE_DOCODE = DOC.DO_CODE
                                           AND RES.RE_DOCOCODE = DOC.DO_COCODE;
                                           
--자유게시판 글 목록 뷰
CREATE OR REPLACE VIEW FBPOSTLIST
AS
select FB_CODE AS FBCODE, FB_DATE AS FBDATE, SU_NAME AS FBSUNAME, FB_TITLE AS FBTITLE, FB_VIEW AS FBVIEW, FB_LIKE AS FBLIKE, FB_SUCODE AS FBSUCODE
from freeboard INNER JOIN SU ON FREEBOARD.FB_SUCODE = SU.SU_CODE;

--자유게시판 글 보기 뷰
CREATE OR REPLACE VIEW FBPOSTCONTENT
AS
select FB_CODE AS FBCODE, FB_DATE AS FBDATE, SU_NAME AS FBSUNAME, FB_TITLE AS FBTITLE, FB_CONTENT AS FBCONTENT, FB_VIEW AS FBVIEW, FB_LIKE AS FBLIKE, FB_SUCODE AS FBSUCODE
from freeboard INNER JOIN SU ON FREEBOARD.FB_SUCODE = SU.SU_CODE;